repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
    files: .*\.java$
- repo: https://github.com/NASA-AMMOS/slim-detect-secrets
  # using commit id for now, will change to tag when official version is released
  rev: 91e097ad4559ae6ab785c883dc5ed989202c7fbe
  hooks:
    - id: detect-secrets
      args:
        - '--baseline'
        - '.secrets.baseline'
        - --exclude-files '\.secrets..*'
        - --exclude-files '\.git.*'
        - --exclude-files '\.pre-commit-config\.yaml'
        - --exclude-files 'target'
- repo: local
  hooks:
    - id: grype-cve-scan
      name: Grype Vulnerability Scan
      description: Scans for dependency vulnerabilities. Fails if CRITICAL vulnerabilities detected.
      entry: python3 -c "import os; import subprocess; import sys; os.environ['GRYPE_DB_AUTO_UPDATE'] = 'false'; result=subprocess.run(['grype', 'dir:.', '--fail-on', 'critical'], capture_output=True); print(result.stdout.decode()); print('CRITICAL level vulnerabilities found. To address issues, run scan via `grype dir:.`, then `git add` followed by `git commit` your fix or ignore via `git commit --no-verify`') if result.returncode != 0 else print('No CRITICAL level vulnerabilities found.'); sys.exit(result.returncode)"
      language: system
      verbose: true
