repos:
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.6.0
  hooks:
  - id: pretty-format-java
    args: [--autofix]
    files: .*\.java$
- repo: https://github.com/NASA-AMMOS/slim-detect-secrets
  # using commit id for now, will change to tag when official version is released
  rev: 91e097ad4559ae6ab785c883dc5ed989202c7fbe
  hooks:
    - id: detect-secrets
      args:
        - '--baseline'
        - '.secrets.baseline'
        - --exclude-files '\.secrets..*'
        - --exclude-files '\.git.*'
        - --exclude-files '\.pre-commit-config\.yaml'
        - --exclude-files 'target'
