# 🏃‍♀️ Continuous Integration and Delivery: Automated Testing
# ======================================================


---

    name: Automated Testing
    
    
    # Driving Event
    # -------------
    #
    # What event starts this workflow: a push to any branch other than main
    
    on:
        push:
            branches:
                -   'automated-testing'
                -   '!main'
        workflow_dispatch:
    
    
    # What to Do
    # ----------
    #
    # Test the software with mvn test
    
    jobs:
        automated-testing:
            name: Automated Testing
            runs-on: ubuntu-latest
            if: github.actor != 'pdsen-ci'
    
            strategy:
                matrix:
                    java-version: [11, 17]
    
            steps:
                -
                    name: 💳 Checkout
                    uses: actions/checkout@v4
                    with:
                        lfs: true
                        fetch-depth: 0
                        token: ${{secrets.ADMIN_GITHUB_TOKEN}}
                -
                    name: 💵 Maven Cache
                    uses: actions/cache@v3
                    with:
                        path: ~/.m2/repository
                        # The "key" used to indicate a set of cached files is the operating system runner
                        # plus "mvn" for Maven-specific builds, plus a hash of the `pom.xml` files, which
                        # should uniquely identify the dependent jars; plus "pds" because we pds-prefix
                        # everything with "pds" in PDS—even when the context is obvious! 😅
                        key: pds-${{runner.os}}-mvn-${{hashFiles('**/pom.xml')}}
                        # To restore a set of files, we only need to match a prefix of the saved key.
                        restore-keys: pds-${{runner.os}}-mvn-
                -
                    name: ☕️ Set up OpenJDK
                    uses: actions/setup-java@v3
                    with:
                        distribution: 'adopt'
                        java-version: ${{matrix.java-version}}
                -
                    name: release-downloader
                    uses: robinraju/release-downloader@v1.8
                    with:
                        tag: v3.4.0-SNAPSHOT
                        fileName: 'validate-3.4.0-SNAPSHOT-bin.zip'
                        out-file-path: 'src/test'
                        extract: true
                
                -
                    name: Test Software
                    run: |
                        chmod +x $GITHUB_WORKSPACE/src/test/validate-3.4.0-SNAPSHOT/bin/validate
                        $GITHUB_WORKSPACE/src/test/validate-3.4.0-SNAPSHOT/bin/validate --version
    
    # -*- mode: yaml; indent: 4; fill-column: 120; coding: utf-8 -*-
    
