# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Weekly Context Config Update

on: push
  # schedule:
  #   - cron:  '0 0 * * 0'

jobs:
  build:
    name: 'Update Context Products from Registry'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Updating context products
      run: |
          build/update_context.sh pdsen-ci@jpl.nasa.gov "PDSEN CI Bot" ${{ secrets.ADMIN_GITHUB_TOKEN }}
          git config --local user.email "pdsen-ci@jpl.nasa.gov"
          git config --local user.name "PDSEN CI Bot"
          git config --local github.token ${{ secrets.ADMIN_GITHUB_TOKEN }}
          git add -A .
          git commit -m "Update config with latest context product metadata"
          git config --global push.default current
          git push
